;Matheus Assuncao Gomes                   19702646
;Matheus Augusto Costa                    19713866
;Gabriel Henrique Coetti                  19711225
TITLE BATALHANAVAL
.MODEL SMALL
.STACK 100H

.DATA

D1 DB '        O  O  O$'
D2 DB '                O$'
D3 DB '               __|__$'
D4 DB '               || ||_____$'
D5 DB '               || ||    |$'
D6 DB '    --------------------------$'
D7 DB '     \   O   O   O   O      /$'
D8 DB ' ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~$'

D9 DB ' _____ _____ _____ _____ __    _____ _____  $'
D10 DB'| __  |  _  |_   _|  _  |  |  |  |  |  _  | $'
D11 DB'| __ -|     | | | |     |  |__|     |     | $'
D12 DB'|_____|__|__| |_| |__|__|_____|__|__|__|__| $'

D13 DB' _____ _____ _____ _____ __  $'
D14 DB'|   | |  _  |  |  |  _  |  | $'
D15 DB'| | | |     |  |  |     |  |__$'
D16 DB'|_|___|__|__|\___/|__|__|_____|$'

NUMEROTB DB '  1 2 3 4 5 6$'
LETRASTB DB 65
ESPACOTB DB ' $' 




TEXTOP1 DB 10,13,"COLOQUE O DESTROIER EM POSICAO (1-TAM): $"
TEXTOP2 DB 10,13,"COLOQUE O FRAGATA EM POSICAO (2-TAM): $"
TEXTOP3 DB 10,13,"COLOQUE O COURACADO EM POSICAO (3-TAM): $"

VENCEDORPLAYER DB 10,13,'FIM DE JOGO - O VENCEDOR FOI : $'

NOME_JOGADOR1 DB 10,13,20 DUP('$')
STRING_POS1 DB 10,13,5 DUP('$')
STRING_POS2 DB 10,13,5 DUP('$')


LINHA_L    DB 13,10,'$'
ESPACAMENTO DB '                    $'

NOME1 DB "DIGITE O NOME DO PRIMEIRO JOGADOR: $"  
NOME2 DB "DIGITE O NOME DO SEGUNDO JOGADOR: $"  

TABELA_JOGADOR1  DB 6 DUP (6 DUP (0))
TABELA_JOGADOR2  DB 6 DUP (6 DUP (0))

VH DB 10,13,'SEU FRAGATA SERA COLOCADO EM HORIZONTAL(H) OU EM VERTICAL(V): $' 

POSI DB 10,13,'DIGITE A POSICAO PARA O NAVIO INDICADO: $'

ENT DB 10,13,'TECLE QUALQUER TECLA PARA COMECAR O POSICIONAMENTO DO SEGUNDO PLAYER: $'

COMECAJOGO DB 10,13,'TECLE QUALQUER TECLA PARA COMECAR O JOGO: $'


DEZ DB (10)

TIROS1 DB 10,13,'TIROS RESTANTES: $'
TIROS1R DB '15$'
TIROS1L DB (15)

TIROS2 DB 10,13,'TIROS RESTANTES: $'
TIROS2R DB '15$'
TIROS2L DB (15)


ACERTOS1 DB 10,13,'ACERTOS: $'
ACERTOS1R DB '0$'
ACERTOS1L DB (0)


ACERTOS2 DB 10,13,'ACERTOS: $'
ACERTOS2R DB '0$'
ACERTOS2L DB(0)

ULTIMO_TIRO DB 10,13,'ULTIMO TIRO: $'

MENORQUEA DB 10,13,'DIGITO NAO IDENTIFICADO$'
NOME_JOGADOR2 DB 10,13,20 DUP('$')

DIGPOS DB 10,13,'DIGITE A POSICAO QUE DEVE SER ATIRADA:$'
SEU_TABULEIRO DB 10,13,'A SITUACAO DO SEU TABULEIRO E$'
TIRO_CORRETO DB 10,13,'TIRO CORRETO! (TECLE PARA CONTINUAR)$'

AGUA DB 10,13,'TIRO NA AGUA!(TECLE PARA CONTINUAR) $'
       

EMPATE DB 10,13,'FIM DE JOGO - EMPATE - FIM DE JOGO $'

LINHAZINHA DB 10,13,'------------------------------------------$'
COMECARBATALHANAVAL DB 10,13,'APERTE QUALQUER TECLA PARA COMECAR O JOGO: $'

             
                     
.CODE
 
 
 
 
 
 

 
 
 
 
 
 
 
 
 MAIN PROC
 ;CHAMANDO O DATA PRA AX
 MOV AX, @DATA
 MOV DS, AX
 
 ;DESENHO ESTICO PARA PAGINA DE INICIO DE JOGO
 MOV AH,9
 LEA DX,D1
 INT 21H
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 
 MOV AH,9
 LEA DX,D2
 INT 21H
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 
 MOV AH,9
 LEA DX,D3
 INT 21H
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 
 MOV AH,9
 LEA DX,D4
 INT 21H
 
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 
 MOV AH,9
 LEA DX,D5
 INT 21H
 
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 
 MOV AH,9
 LEA DX,D6
 INT 21H
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 
 MOV AH,9
 LEA DX,D7
 INT 21H
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 
 MOV AH,9
 LEA DX,D8
 INT 21H
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 
 MOV AH,9
 LEA DX,D8
 INT 21H
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 
 ;BARCO
 MOV AH,9
 LEA DX,D9
 INT 21H
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 MOV AH,9
 LEA DX,D10
 INT 21H
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 MOV AH,9
 LEA DX,D11
 INT 21H
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 MOV AH,9
 LEA DX,D12
 INT 21H
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 MOV AH,9
 LEA DX,D13
 INT 21H
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 MOV AH,9
 LEA DX,D14
 INT 21H
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 MOV AH,9
 LEA DX,D15
 INT 21H
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 MOV AH,9
 LEA DX,D16
 INT 21H
 MOV AH,9
 LEA DX,LINHA_L
 INT 21H
 
 
 
 
 MOV AH,9
 LEA DX,COMECARBATALHANAVAL
 INT 21H
 
 MOV AH,7
 INT 21H
 
 CALL LIMPATELA
 
 
 
 

 ;CHAMANDO O PROCEDIMENTO PARA ARMAZENAR O PRIMEIRO NOME
 CALL NOMES
 ;CHAMANDO O PROCEDIMENTO PARA LIMPAR A TELA
 CALL LIMPATELA
 
 ;ESCREVENDO NOME ARMAZENADO NA TELA
 LEA DX,NOME_JOGADOR1
 MOV AH, 9
 INT 21H
 ;ZERANDO VARIAVEIS DE INDICE
 XOR DX,DX
 XOR SI,SI
 ;PASSANDO TEXTO DO DATA
 LEA DX,TEXTOP1
 MOV AH, 9
 INT 21H
 
 XOR DX,DX
 XOR SI,SI
 ;PASSADNO TEXTO DO DATA
 LEA DX,LINHA_L
 MOV AH, 9
 INT 21H
 

 ;CHAMANDO O PROCEDIMENTO DE MOSTRAR TABULEIRO PARA TABELA JOGADOR 1 PASSADA EM SI
 LEA SI,TABELA_JOGADOR1
 MOV CH,6
 CALL MOSTRA_TABULEIRO 
 MOV CX,0
 
 
 
 ;PASSANDO 2 PARA A LEITURA DE 2 DESTROIERS 
 MOV CX,2
 ;ROTULO PARA LER DESTROIER
 LERDESTROIER:
 JMP PULO
 IGUAL:
 ;ESCREVENDO ERRO
 MOV AH,9
 LEA DX,MENORQUEA
 INT 21H
 
 PULO:
 ;CHAMANDO PROCEDIMENTO PARA INDICAR DESTROIER
 CALL INDICAR_POSICAO_DESTROIER
 CMP TABELA_JOGADOR1[BX+SI], 30
 JE IGUAL
 MOV TABELA_JOGADOR1[BX+SI], 30
 LOOP LERDESTROIER
 
 CALL LIMPATELA
 
 ;MONTAGEM DO CABECARIO 
 LEA DX,NOME_JOGADOR1
 MOV AH, 9
 INT 21H
 
 XOR DX,DX
 XOR SI,SI
 
 ;TEXTO PARA INDICAR O TIPO DE NAVIO
 
 LEA DX,TEXTOP2
 MOV AH, 9
 INT 21H
 
 XOR DX,DX
 XOR SI,SI
 
 ;PULAR LINHA
 
 LEA DX,LINHA_L
 MOV AH, 9
 INT 21H
 
;MOSTRANDO TABULEIRO
 
 LEA SI,TABELA_JOGADOR1
 MOV CH,6
 CALL MOSTRA_TABULEIRO



 MOV CX,0
 
 
 ;PASSANDO 2 PARA A LEITURA DE 2  FRAGATA
 MOV CX,2
 LERFRAGATA:
 JMP PULOF
 IGUALF:
 ;LENDO ERRO
 MOV AH,9
 LEA DX,MENORQUEA
 INT 21H
 ;LEITURA DE POSICIONAMENTO VERTICAL OU HORIZONTAL
 PULOF:    
  MOV AH,9
  LEA DX,VH
  INT 21H
  ;PEGANDO DIGITOS DO TECLADO
  MOV AH,7
  INT 21H
  
  ;USANDO A MASCARA PARA PASSAR OS VALORES RESGATADOS DO TECLA EM LETRA MAIUSCULA
  AND AL, 11011111B
  ;COMPARANDO VALORES PARA VALIDACAO
  CMP AL,72
  ;VALIDACAO PARA SELECIONAR SOMENTE H 
 JZ HORIZONTAL
 CMP AL,86
 ;VALIDACAO PARA SELECIONAR SOMENTE V
 JZ VERTICAL
 ;CASO NAO SEJA NEM V NEM H ELE PULA PRA IGUALF E APRESENTA MENSAGEM DE ERRO
 JMP IGUALF
 ;CASO SEJA SELECIONADO O H FAZ A INDICACAO DA POSICAO E OS TESTES
 HORIZONTAL:
 CALL INDICAR_POSICAO_FRAGATA
 CMP TABELA_JOGADOR1[BX+SI], 30
 JE IGUALF
 MOV TABELA_JOGADOR1[BX+SI], 30
 INC SI
 MOV TABELA_JOGADOR1[BX+SI],30
 LOOP LERFRAGATA
 
 JMP CONTINUAA
 ;CASO SEJA SELECIONADO O V FAZ A INDICACAO DA POSICAO E OS TESTES
 VERTICAL:
 CALL INDICAR_POSICAO_FRAGATA
 CMP TABELA_JOGADOR1[BX+SI],30
 JE IGUALF
 MOV TABELA_JOGADOR1[BX+SI],30
 ADD SI,6
 MOV TABELA_JOGADOR1[BX+SI],30
 LOOP LERFRAGATA
  
 CONTINUAA:
 
 ;PROCEDIMENTO DE LIMPAR A TELA
 CALL LIMPATELA
 
 ;CABE?ARIO PARA O 3 NAVIO COURACADO
 LEA DX,NOME_JOGADOR1
 MOV AH, 9
 INT 21H
 
 XOR DX,DX
 XOR SI,SI
 
 LEA DX,TEXTOP3
 MOV AH, 9
 INT 21H
 
 XOR DX,DX
 XOR SI,SI
 
 LEA DX,LINHA_L
 MOV AH, 9
 INT 21H
 
 LEA SI,TABELA_JOGADOR1
 MOV CH,6
 CALL MOSTRA_TABULEIRO
 
 MOV CX,0
 ;INDICACAO DO 3 TIPO DE NAVIO COURACADO TAM 3
 MOV CX,1
 LERCOURACADO:
 JMP PULOC
 IGUALC:
 ;CASO DE ERRO MENSAGEM DE ERRO
 MOV AH,9
 LEA DX,MENORQUEA
 INT 21H
 PULOC:
  MOV AH,9
  LEA DX,VH
  INT 21H
  
  MOV AH,7
  INT 21H
  ;PEGANDO LETRA MAIUSCULA EM ASC
  AND AL, 11011111B
  ;COMPARANDO COM H
  CMP AL,72
  ;SE FOR IGUAL ENTRA COM POSICIONAMENTO EM HORIZONTAL
  JZ HORIZONTALC
  ;COMPARANDI COM V
  CMP AL,86
  ;SE FOR IGUAL ENTRA NO POSICIONAMENTO EM VERTICAL
  JZ VERTICALC
  JMP IGUALC
 
  ;POSICIONAMENTO EM HORIZONTAL COMO SAO 3 POSICOES A ESCOLHA DO USARIO REFLETE A DO MEIO
 HORIZONTALC:
 CALL INDICAR_POSICAO_COURACADO
 CMP TABELA_JOGADOR1[BX+SI], 30
 JE IGUALC
 MOV TABELA_JOGADOR1[BX+SI], 30
 DEC SI
 MOV TABELA_JOGADOR1[BX+SI],30
 ADD SI,2
 MOV TABELA_JOGADOR1[BX+SI],30
 LOOP LERCOURACADO
 
 JMP CONTINUAAA
 ;POSICIONAMENTO EM VERTICAL COMO SAO 3 POSICOES A ESCOLHA DO USARIO REFLETE A DO MEIO
 VERTICALC:
 CALL INDICAR_POSICAO_COURACADO
 CMP TABELA_JOGADOR1[BX+SI], 30
 JE IGUALC
 MOV TABELA_JOGADOR1[BX+SI], 30
 SUB SI,6
 MOV TABELA_JOGADOR1[BX+SI],30
 ADD SI,12
 MOV TABELA_JOGADOR1[BX+SI],30
 LOOP LERCOURACADO
  
 CONTINUAAA:
 ;MOSTRANDO AO JOGADOR COMO FICOU O POSICIONAMENTO DE SEUS BARCOS
 
 CALL LIMPATELA
 LEA DX,NOME_JOGADOR1
 MOV AH, 9
 INT 21H
 
 XOR DX,DX
 XOR SI,SI
 
 LEA DX,LINHA_L
 MOV AH, 9
 INT 21H
 
 LEA SI,TABELA_JOGADOR1
 MOV CH,6
 CALL MOSTRA_TABULEIRO
 
 MOV AH,9
 LEA DX,ENT
 INT 21H
 
 MOV AH,7
 INT 21H
 
 ;PLAYER 2------------------------------SEMELHANTE AO JOGADOR 1-------------------------------------------------------------------------------------------------------------
 CALL LIMPATELA
 
  CALL NOMES2
  
 CALL LIMPATELA
 
 
 LEA DX,NOME_JOGADOR2
 MOV AH, 9
 INT 21H
 
 XOR DX,DX
 XOR SI,SI
 
 LEA DX,TEXTOP1
 MOV AH, 9
 INT 21H
 
 XOR DX,DX
 XOR SI,SI
 
 LEA DX,LINHA_L
 MOV AH, 9
 INT 21H
 

 
 LEA SI,TABELA_JOGADOR2
 MOV CH,6
 CALL MOSTRA_TABULEIRO 
 MOV CX,0
 MOV CX,2
 LERDESTROIER2:
 JMP PULO2
 IGUAL2:
 MOV AH,9
 LEA DX,MENORQUEA
 INT 21H
 
 PULO2:
 CALL INDICAR_POSICAO_DESTROIER
 CMP TABELA_JOGADOR2[BX+SI], 30
 JE IGUAL2
 MOV TABELA_JOGADOR2[BX+SI], 30
 LOOP LERDESTROIER2
 
 CALL LIMPATELA
 
  
 LEA DX,NOME_JOGADOR2
 MOV AH, 9
 INT 21H
 
 XOR DX,DX
 XOR SI,SI
 
 LEA DX,TEXTOP2
 MOV AH, 9
 INT 21H
 
 XOR DX,DX
 XOR SI,SI
 
 LEA DX,LINHA_L
 MOV AH, 9
 INT 21H
 
 LEA SI,TABELA_JOGADOR2
 MOV CH,6
 CALL MOSTRA_TABULEIRO



 MOV CX,0
 MOV CX,2
 LERFRAGATA2:
 JMP PULOF2
 IGUALF2:
 MOV AH,9
 LEA DX,MENORQUEA
 INT 21H
 
 PULOF2:    
  MOV AH,9
  LEA DX,VH
  INT 21H
  
  MOV AH,7
  INT 21H
  
  AND AL, 11011111B
  CMP AL,72
  JZ HORIZONTAL2
 CMP AL,86
 JZ VERTICAL2
 JMP IGUALF2
 
 HORIZONTAL2:
 CALL INDICAR_POSICAO_FRAGATA
 CMP TABELA_JOGADOR2[BX+SI], 30
 JE IGUALF2
 MOV TABELA_JOGADOR2[BX+SI], 30
 INC SI
 MOV TABELA_JOGADOR2[BX+SI],30
 LOOP LERFRAGATA2
 
 JMP CONTINUAA2

 VERTICAL2:
 CALL INDICAR_POSICAO_FRAGATA
 CMP TABELA_JOGADOR2[BX+SI], 30
 JE IGUALF2
 MOV TABELA_JOGADOR2[BX+SI], 30
 ADD SI,6
 MOV TABELA_JOGADOR2[BX+SI],30
 LOOP LERFRAGATA2
  
 CONTINUAA2:
 
 
 CALL LIMPATELA
 
  
 LEA DX,NOME_JOGADOR2
 MOV AH, 9
 INT 21H
 
 XOR DX,DX
 XOR SI,SI
 
 LEA DX,TEXTOP3
 MOV AH, 9
 INT 21H
 
 XOR DX,DX
 XOR SI,SI
 
 LEA DX,LINHA_L
 MOV AH, 9
 INT 21H
 
 LEA SI,TABELA_JOGADOR2
 MOV CH,6
 CALL MOSTRA_TABULEIRO
 
 MOV CX,0
 MOV CX,1
 LERCOURACADO2:
 JMP PULOC2
 IGUALC2:
 MOV AH,9
 LEA DX,MENORQUEA
 INT 21H
 
 PULOC2:
  MOV AH,9
  LEA DX,VH
  INT 21H
  
  MOV AH,7
  INT 21H
  
  AND AL, 11011111B
  CMP AL,72
  JZ HORIZONTALC2
  CMP AL,86
  JZ VERTICALC2
  JMP IGUALC2
 
 
  HORIZONTALC2:
 CALL INDICAR_POSICAO_COURACADO
 CMP TABELA_JOGADOR2[BX+SI], 30
 JE IGUALC2
 MOV TABELA_JOGADOR2[BX+SI], 30
 DEC SI
 MOV TABELA_JOGADOR2[BX+SI],30
 ADD SI,2
 MOV TABELA_JOGADOR2[BX+SI],30
 LOOP LERCOURACADO2
 
 JMP CONTINUAAA2

 VERTICALC2:
 CALL INDICAR_POSICAO_COURACADO
 CMP TABELA_JOGADOR2[BX+SI], 30
 JE IGUALC2
 MOV TABELA_JOGADOR2[BX+SI], 30
 SUB SI,6
 MOV TABELA_JOGADOR2[BX+SI],30
 ADD SI,12
 MOV TABELA_JOGADOR2[BX+SI],30
 LOOP LERCOURACADO2
  
 CONTINUAAA2:
 
 CALL LIMPATELA
 LEA DX,NOME_JOGADOR2
 MOV AH, 9
 INT 21H
 
 XOR DX,DX
 XOR SI,SI
 
 LEA DX,LINHA_L
 MOV AH, 9
 INT 21H
 
 LEA SI,TABELA_JOGADOR2
 MOV CH,6
 CALL MOSTRA_TABULEIRO
 
 MOV AH,9
 LEA DX,COMECAJOGO
 INT 21H
 
 MOV AH,7
 INT 21H
 
 
 ;----------------------------------------------COMECA JOGO--------------------------------------------------------------------------------------------
 ;PASSANDO 15 PARA AS 15 JOGADAS QUE DEVEM TER CADA JOGADOR 
 MOV CX,15
 ;ROTULO DE COMECO DE JOGO
 COMECATIROTEIO:
 ;PROCEDIMENTO DE LIMPAR TELA
 CALL LIMPATELA
 
 ;CHAMANDO BOLETIM DO PRIMERIO JOGADOR COM SUAS INFORMACOES
 CALL BOLETIMP1
 ;TEXTO DE INFORMACAO
 MOV AH,9
 LEA DX,SEU_TABULEIRO
 INT 21H
 ;PULA LINHA
 LEA DX,LINHA_L
 MOV AH, 9
 INT 21H
 
 ;MOSTRA A TABELA DO JOGADOR1
 LEA SI,TABELA_JOGADOR1
 CALL MOSTRA_TABULEIRO
 
 ;TEXTO PARA INFORMAR A POSICAO
 MOV AH,9
 LEA DX,DIGPOS
 INT 21H
 
  ;PROCEDIMENTO PARA PEGAR A POSICAO DO TIRO
 
 CALL TIROP1
 ;PROCEDIMENTO PARA VERIFICAR E ATIRAR NA POSICAO
 CALL VALIDACAOTIROP1
 
 ;PROCEDIMENTO PARA VER SE O PLAYER 1 GANHO
 CALL VALIDACAOVENCEDOR1
 ;LIMPA TELA
 CALL LIMPATELA 
 
 ;BOLETIM DE ACONTECIMENTOS O JOGADOR 2
 CALL BOLETIMP2
 ;TEXTO INFORMATIVO
 MOV AH,9
 LEA DX,SEU_TABULEIRO
 INT 21H
 ;PULA LINHA
 LEA DX,LINHA_L
 MOV AH, 9
 INT 21H
 ;MOSTRAR TABELA SEGUNDO JOGADOR
 LEA SI,TABELA_JOGADOR2
 CALL MOSTRA_TABULEIRO
 ;TEXTO DE INFORMATIVO DE PROCEDIMENTO
 MOV AH,9
 LEA DX,DIGPOS
 INT 21H
 ;PROCEDIMENTO PARA PEGAR A POSICAO DO TIRO
 CALL TIROP2
 ;PROCEDIMENTO PARA VERIFICAR E ATIRAR NA POSICAO
 CALL VALIDACAOTIROP2
 ;VALIDA DE JOGADOR 2 VENCEU
 CALL VALIDACAOVENCEDOR2
 ;TERMINA O LOOP DE 15 TIROS
LOOP COMECATIROTEIO

;LIMPA A TELA
CALL LIMPATELA
;PROCEDIMENTOS PARA VER SE HOUVE VENCEDORES DEVIDO AO NUMERO DE TIROS ACERTOS E NAO POR DESTRUICAO TOTAL
CALL VENCEDOR_COM_TIROS

;CHAMA TEXTO DE EMPATE
MOV AH,9
LEA DX,EMPATE
INT 21H
 
;FINALIZA
MOV AH,4CH
INT 21H

ENDP MAIN
;PROCEDIMENTO PARA VER VENCEDORES COM TIROS E SEM DETRUICAO DE TODOS OS NAVIOS
 VENCEDOR_COM_TIROS PROC
 ;LENDO OS VETORES DE ACERTOS
 LEA SI,[ACERTOS1L]
 LEA DI,[ACERTOS2L]
 MOV AL,[SI]
 MOV BL,[DI]
 ;PULA PARA VALIDACAO
 JMP TESTEEMP
 ;ROTULO DE VENCEDOR PARA O PRIMEIRO JOGADOR
 VENCEDORP1:
 
   CALL LIMPATELA

    MOV AH,9
    LEA DX,VENCEDORPLAYER
    INT 21H
    MOV AH,9
    LEA DX,NOME_JOGADOR1
    INT 21H
    MOV AH,4CH
    INT 21H
    
    ;ROTULO DE VENCEDOR PARA SEGUNDO JOGADOR
    VENCEDORP2:
    CALL LIMPATELA

    MOV AH,9
    LEA DX,VENCEDORPLAYER
    INT 21H
    MOV AH,9
    LEA DX,NOME_JOGADOR2
    INT 21H
    
    MOV AH,4CH
    INT 21H
    TESTEEMP:
    ;COMPARANDO O VALOR DE TIROS ACERTADOS DO PRIMEIRO COM O SEGUNDO JOGADOR
    CMP AL,BL
    ;SE O PRIMERIO JOGADOR FOR MAIOR QUE O DO SEGUNDO PULA PARA VENCEDORP1
    JG VENCEDORP1
    CMP AL,BL
    ;SE FOR MENRO VAI PARA VENCEDOR P2
    JL VENCEDORP2
    ;CASO SEJA IGUAL CONTINUA E DECLARA EMPATE
    RET
 ENDP VENCEDOR_COM_TIROS
 ;BOLETIM DE ESCRITA DO PRIMEIRO JOGADOR
BOLETIMP1 PROC
;PRINTA QUESTOES GRAFICAS E TEXTOS
MOV AH,9
LEA DX,LINHAZINHA
INT 21H

MOV AH,9
LEA DX,LINHA_L
INT 21H


MOV AH,9
LEA DX,NOME_JOGADOR1
INT 21H

MOV AH,9
LEA DX,TIROS1
INT 21H
;ZERANDO AX PARA PRINTAR A QUANTIDADE DE TENTATIVAS AINDA RESTAO NA TELA
XOR AX,AX
;MOVENDO O VALOR DE TIROS RESTANTES EM AL
MOV AL,TIROS1L
;CHAMANDO PROCEDIMENTO DE ESCRITA
CALL TIROS_RESTANTES
;DIMINUINDO AS TENTATIVAS
DEC TIROS1L

;NUMERO DE ACERTOS
MOV AH,9
LEA DX,ACERTOS1
INT 21H


MOV AH,9
LEA DX,ACERTOS1R
INT 21H
;LOCAL DE ULTIMO TIRO
MOV AH,9
LEA DX,ULTIMO_TIRO
INT 21H

MOV AH,9
LEA DX,STRING_POS1
INT 21H

MOV AH,9
LEA DX,LINHAZINHA
INT 21H


RET

ENDP BOLETIMP1



;PROCEDIMENTO IGUAL AO BOLETIM 1 POREM PARA 2 JOGADOR
BOLETIMP2 PROC

MOV AH,9
LEA DX,LINHAZINHA
INT 21H

MOV AH,9
LEA DX,LINHA_L
INT 21H


MOV AH,9
LEA DX,NOME_JOGADOR2
INT 21H

MOV AH,9
LEA DX,TIROS1
INT 21H


XOR AX,AX
MOV AL,TIROS2L
CALL TIROS_RESTANTES

MOV AH,9
LEA DX,ACERTOS2
INT 21H

MOV AH,9
LEA DX,ACERTOS2R
INT 21H

DEC TIROS2L

MOV AH,9
LEA DX,ULTIMO_TIRO
INT 21H

MOV AH,9
LEA DX,STRING_POS2
INT 21H



MOV AH,9
LEA DX,LINHAZINHA
INT 21H


RET

ENDP BOLETIMP2

;VALIDANDO VENCEDOR
VALIDACAOVENCEDOR2 PROC
JMP TESTEV2
VENCEDOR2:
;VENCEDOR 2 DECLARA JOGADOR 2 VENCEDOR E ENCERRA O PROGRAMA
CALL LIMPATELA
MOV AH,9
LEA DX,VENCEDORPLAYER
INT 21H
MOV AH,9
LEA DX,NOME_JOGADOR2
INT 21H

MOV AH,4CH
INT 21H

TESTEV2:
;COMPARA O NUMERO DE ACERTOS A 9 QUANTIDADE DE POSICOES A SEREM ACERTADAS COM RELACAO AO NUMERO DE BARCOS E SEUS TIPOS
CMP ACERTOS2L,9
;CASO SEJA IGUAL VAI PARA VENCEDOR 2
JE VENCEDOR2

RET
ENDP VALIDACAOVENCEDOR2
;IDENTICO AO VENCEDOR2 POREM PARA O 1 PLAYER
VALIDACAOVENCEDOR1 PROC
JMP TESTEV
VENCEDOR1:
CALL LIMPATELA
MOV AH,9
LEA DX,VENCEDORPLAYER
INT 21H
MOV AH,9
LEA DX,NOME_JOGADOR1
INT 21H

MOV AH,4CH
INT 21H

TESTEV:
CMP ACERTOS1L,9
JE VENCEDOR1

RET
ENDP VALIDACAOVENCEDOR1


;TIRO P2 PEGA A POSICAO A SER ATIRADA
TIROP2 PROC
  XOR BX, BX ;MOV BX, 0 
  XOR SI, SI ;MOV SI, 0 
  XOR DI,DI
  LEA DI,STRING_POS2

  JMP MSGT2  
   DIFERET2:
   ;CASO A POSICAO NAO EXISTA DECLARA ERRO
    MOV AH, 9
    LEA DX, MENORQUEA
    INT 21H
    ;PEGANDO A POSICAO REFERENTE A LETRA
    MSGT2:
    MOV AH, 7
    INT 21H
    
    ;CONVERTE TEXTO PRA MAIUSCULO
    AND AL, 11011111B
    
    CMP AL, 65
    ;MENOR QUE A
    JB DIFERET2
    
    CMP AL,70
    ;MAIOR QUE J
    JA DIFERET2
    MOV [DI],AL
    
    MOV BL, AL
    SUB BL, 65
    
    
    ;SE FOR = A
    JZ LTIRO2
    
    
            
    MOV DL, BL
    XOR BL, BL 

    
    
    LINHAT2:
    ;INDICANDO A POSICAO DA LINHA 
    ADD BL, 6

    DEC DL
    JNZ LINHAT2
    
    
    ;PEGANDO POSICAO REFERENTE AO NUMERO
    LTIRO2:
    XOR BH, BH 
    ;PEGA O NUMERO
    MOV AH, 7
    INT 21H
    
    
    CMP AL, 49
    ;MENOR QUE 1
    JB DIFERET2
    CMP AL, 54
    ;MAIOR QUE 6
    JA DIFERET2
    INC DI
    MOV[DI],AL
    
    

    SUB AL,49
    ;IGUAL AO 1
    JZ PPT2
    
    XOR SI, SI
    MOV DH, AL
        
    

    COLUNAT2:
    ;INDICANDO A POSICAO DA COLINA
    INC SI
    DEC DH
    JNZ COLUNAT2
  
    PPT2:
    
    
    RET
    ENDP TIROP2

    ;VALIDANDO A POSICAO ESCOLHIDA PARA TIRO DO PLAYER 2
VALIDACAOTIROP2 PROC
JMP VALDTIRO2
IGUALT2:
;POSICIONA 2 QUE INDICA QUE ACERTOU
MOV TABELA_JOGADOR1[BX+SI],40
;INCREMENTA ACERTOS
INC ACERTOS2R
INC ACERTOS2L
;DIZ QUE ACERTOU
MOV AH,9
LEA DX,TIRO_CORRETO
INT 21H
;ESPERA DIGITACAO PARA CONTINUAR
MOV AH,7
INT 21H

RET

VALDTIRO2:
CMP TABELA_JOGADOR1[BX+SI],30
JE IGUALT2
;CASO TENHA ERRADO MOSTRA QUE TIRO FOI NA AGUA
MOV AH,9
LEA DX,AGUA
INT 21H
;ESPERA UM DIGITO PARA PROCESEGUIR
MOV AH,7
INT 21H

RET

ENDP VALIDACAOTIROP2
;EXATAMENTE A VALIDA TIRO 2

VALIDACAOTIROP1 PROC
JMP VALDTIRO1
IGUALT1:
MOV TABELA_JOGADOR2[BX+SI],40
INC ACERTOS1R
INC ACERTOS1L

MOV AH,9
LEA DX,TIRO_CORRETO
INT 21H

MOV AH,7
INT 21H

RET

VALDTIRO1:
CMP TABELA_JOGADOR2[BX+SI],30
JE IGUALT1

MOV AH,9
LEA DX,AGUA
INT 21H

MOV AH,7
INT 21H

RET

ENDP VALIDACAOTIROP1

TIROP1 PROC
  XOR BX, BX ;MOV BX, 0 
  XOR SI, SI ;MOV SI, 0 
  XOR DI, DI
  LEA DI,STRING_POS1


  JMP MSGT  
   DIFERET:
    MOV AH, 9
    LEA DX, MENORQUEA
    INT 21H
    

    MSGT:
    MOV AH, 7
    INT 21H
    
    ;CONVERTE TEXTO PRA MAIUSCULO
    AND AL, 11011111B
    
    CMP AL, 65
    ;MENOR QUE A
    JB DIFERET
    
    CMP AL,70
    ;MAIOR QUE J
    JA DIFERET
    MOV [DI],AL 
    
     MOV BL, AL
    SUB BL, 65
    
    
    ;SE FOR = A
    JZ LTIRO
    
    
            
    MOV DL, BL
    XOR BL, BL 

    
    
    LINHAT:
    ;INDICANDO A POSICAO DA LINHA 
    ADD BL, 6

    DEC DL
    JNZ LINHAT
    
    

    LTIRO:
    XOR BH, BH 
    ;PEGA O NUMERO
    MOV AH, 7
    INT 21H
    
    
    CMP AL, 49
    ;MENOR QUE 1
    JB DIFERET
    CMP AL, 54
    ;MAIOR QUE 6
    JA DIFERET
    INC DI
    MOV [DI],AL
    

    SUB AL,49
    ;IGUAL AO 1
    JZ PPT
    
    XOR SI, SI
    MOV DH, AL
        
    

    COLUNAT:
    ;INDICANDO A POSICAO DA COLINA
    INC SI
    DEC DH
    JNZ COLUNAT
  
    PPT:
    
    
    RET
ENDP TIROP1

;SEGURA POSICAO PARA COLOCAR O COURACADO TAM3
INDICAR_POSICAO_COURACADO PROC
  XOR BX, BX ;MOV BX, 0 
  XOR SI, SI ;MOV SI, 0 
    
  JMP VALIDACAOC 
  DIFEREC:
  ;CASO A POSICAO NAO EXISTA MOSTTA MENSAGEM DE ERRO
  MOV AH, 9
  LEA DX, MENORQUEA
  INT 21H

  ;VALIDADANDO POSICAO
  
  VALIDACAOC:
    MOV AH, 9
    LEA DX, POSI
    INT 21H

    MOV AH, 7
    INT 21H
    
    ;PEGANDO LETRA ,MAIUSCULA
    AND AL, 11011111B
    CMP AL, 65
    ;MENOR QUE A
    JB DIFEREC
    
    CMP AL,70
    ;MAIOR QUE J
    JA DIFEREC
    
     MOV BL, AL
    SUB BL, 65
    
    
    ;SE FOR = A
    JZ LC
    
    
            
    MOV DL, BL
    XOR BL, BL 

    
    
    LINHAC:
    ;INDICANDO A POSICAO DA LINHA 
    ADD BL, 6

    DEC DL
    JNZ LINHAC
    
    

    LC:
    XOR BH, BH 
    ;PEGA O NUMERO
    MOV AH, 7
    INT 21H
    CMP AL, 49
    ;MENOR QUE 1
    JB DIFEREC
    CMP AL, 54
    ;MAIOR QUE 6
    JA DIFEREC
    
    

    SUB AL,49
    ;IGUAL AO 1
    JZ PP_C
    
    XOR SI, SI
    MOV DH, AL
        
    

    COLUNAC:
    ;INDICANDO A POSICAO DA COLINA
    INC SI
    DEC DH
    JNZ COLUNAC
    

  
    PP_C:
    RET
  
    ENDP INDICAR_POSICAO_COURACADO

    ;PEGANDO POSICAO PARA ALOCACAO DA FRAGATA TAM 2
INDICAR_POSICAO_FRAGATA PROC
  XOR BX, BX ;MOV BX, 0 
  XOR SI, SI ;MOV SI, 0 
    
  JMP VALIDACAOF
  DIFEREF:
  MOV AH, 9
  LEA DX, MENORQUEA
  INT 21H
  
  
  VALIDACAOF:
    MOV AH, 9
    LEA DX, POSI
    INT 21H

    MOV AH, 7
    INT 21H
    
    ;PASSANDO LETRA MAIUSCULA
    AND AL, 11011111B
    CMP AL, 65
    ;MENOR QUE A
    JB DIFEREF
    
    CMP AL,70
    ;MAIOR QUE J
    JA DIFEREF
    
     MOV BL, AL
     SUB BL, 65
    
    
    ;SE FOR = A
    JZ LF
    
    
            
    MOV DL, BL
    XOR BL, BL 

    
    
    LINHAF:
    ;INDICANDO A POSICAO DA LINHA 
    ADD BL, 6

    DEC DL
    JNZ LINHAF
    
    

    LF:
    XOR BH, BH 
    ;PEGA O NUMERO
    MOV AH, 7
    INT 21H
    CMP AL, 49
    ;MENOR QUE 1
    JB DIFEREF
    CMP AL, 54
    ;MAIOR QUE 6
    JA DIFEREF
    
    

    SUB AL,49
    ;IGUAL AO 1
    JZ PP_F
    
    XOR SI, SI
    MOV DH, AL
        
    

    COLUNAF:
    ;INDICANDO A POSICAO DA COLINA
    INC SI
    DEC DH
    JNZ COLUNAF
    

  
    PP_F:
    RET
  
    ENDP INDICAR_POSICAO_FRAGATA

    ;PEGANDO POSICAO DO DESTROIER
INDICAR_POSICAO_DESTROIER PROC
  XOR BX, BX ;MOV BX, 0 
  XOR SI, SI ;MOV SI, 0 

   JMP MSGD

    DIFERED:
    ;MENSAGEM DE ERRO
    MOV AH, 9
    LEA DX, MENORQUEA
    INT 21H

    MSGD:
    MOV AH, 9
    LEA DX, POSI
    INT 21H

    MOV AH, 7
    INT 21H
    
    ;CONVERTE TEXTO PRA MAIUSCULO
    AND AL, 11011111B
    CMP AL, 65
    ;MENOR QUE A
    JB DIFERED
    
    CMP AL,70
    ;MAIOR QUE ou igyualJ
    JA DIFERED
    
     MOV BL, AL
    SUB BL, 65
    
    
    ;SE FOR = A
    JZ LD
    
    
            
    MOV DL, BL
    XOR BL, BL 

    
    
    LINHAD:
    ;INDICANDO A POSICAO DA LINHA 
    ADD BL, 6

    DEC DL
    JNZ LINHAD
    
    

    LD:
    XOR BH, BH 
    ;PEGA O NUMERO
    MOV AH, 7
    INT 21H
    CMP AL, 49
    ;MENOR QUE 1
    JB DIFERED
    CMP AL, 54
    ;MAIOR QUE 6
    JA DIFERED
    
    

    SUB AL,49
    ;IGUAL AO 1
    JZ PPD
    
    XOR SI, SI
    MOV DH, AL
        
    

    COLUNAD:
    ;INDICANDO A POSICAO DA COLINA
    INC SI
    DEC DH
    JNZ COLUNAD
  
    PPD:
    
    
    RET
ENDP INDICAR_POSICAO_DESTROIER
;IMPRIMI TABULEIRO
MOSTRA_TABULEIRO PROC
    MOV LETRASTB,65

    MOV AH,9
    LEA DX,NUMEROTB
    INT 21H

;PULA LINHA
    MOV AH,9
    LEA DX, LINHA_L
    INT 21H
    ;GUARDANDO CX NA PILHA
    PUSH CX
    ;PASSANDO 6 PRO LOOP
    MOV CH,6 
    LACO_FORA:
    MOV AH,2
    MOV DL,LETRASTB
    INT 21H
    INC LETRASTB
    MOV AH,2
    MOV DL,' '
    INT 21H
    ;movendo 2 a ah para a chamada de leitura
      MOV AH,2
      ;movendo 6 para o loop intertno de laco dentro
      MOV CL,6
      ;zerando o valor do indice
      XOR BX,BX
      LACO_DENTRO:
        
        ;movendo o valor da matriz auxiliar que sera lida em dl
        MOV DL, [SI+BX]
        ;adicionando 30h para se adequar a tabela ascii
        ADD DL, 30H
        ;chamando a funcao em ah que no caso e a escrita em tela
        INT 21H
        
        MOV AH,2
        MOV DL,' '
        INT 21H
        
        
        ;incrementa o bx
        INC BX
        ;decrementa o loop
        DEC CL
        JNZ LACO_DENTRO
        ;passa a funcao de pular linha
        
        MOV AH,9
        LEA DX, LINHA_L
        INT 21H
     ;adiciona 4 a matriz
     ADD SI,6
     ;decrementa o loop de fora
     DEC CH
     JNZ LACO_FORA
     POP CX
     RET
MOSTRA_TABULEIRO ENDP
    ;FUNCAO DE LIMPAR A TELA
    ; E RETORNAR A POSICAO DE INDICADOR 1
  LIMPATELA PROC
    MOV AH,00H
    MOV AL,3
    INT 10H
    RET
ENDP LIMPATELA  
  ;FUNCAO PARA PEGAR A STRING
PEGA_STRING PROC
 ;ZERANDO AX
 XOR AX,AX
 LACO:
 ;FUNCAO DE LEITURA DE TECLADO
 MOV AH,1
 INT 21H
 ;COMPARANDO COM ENTER TABELA ASC PARA QUANDO DEREM ENTER PARAR DE ARMAZENAR A STRING
 CMP AL,00001101b
 JE LACO2
 ;MOVENDO A LETRA PARA A STRING
 MOV [SI],AL
 ;INCREMENTANDO O VETOR PARA ARMAZENAR A PROXIMA LETRA
 INC SI
 JMP LACO
 LACO2:
 RET
 ENDP PEGA_STRING
 
 
 
 
 
 
 
 

 
 
 
 
 
 
 

 ;PROCEDIMENTO DE LEITURA
 NOMES PROC
 ;TEXTO DE LEITURA
  MOV AH,9
  LEA DX,NOME1
  INT 21H
  ;PASSANDO O VETOR EM SI
  LEA SI,NOME_JOGADOR1
  ;CHAMANDO A FUNCAO PARA ARMAZENAR A STRING DE NOME
  CALL PEGA_STRING
  
 RET 
 
 ENDP NOMES
 ;MESMA COISA DE NOMES 1 POREM COM TEXTOS E VETORES DO PLAYER 2
  NOMES2 PROC
 
  MOV AH,9
  LEA DX,NOME2
  INT 21H
  LEA SI,NOME_JOGADOR2
  CALL PEGA_STRING
  
 RET 
 
 
 ENDP NOMES2
 
 ;FUNCAO DE STRING RESTANTE
 ;ASSIM COMO NO LABORARIO 5 NO QUAL A GENTE MOSTROU O NUMERO DIVISIVEL E SEU DIVIDENDO E RESTO USA-SE ESSA ESTRATEGIA PARA CORTAR O 15 E PRINYALO
 
 TIROS_RESTANTES PROC
 
     ;DIVIDI 10
    DIV DEZ
    ;PASSA O RESTO [RA BL
    MOV BH,AH
    MOV BL,AL

    ;CHAMA FUNCAO DE PRINT
    MOV AH,2
    ;PASSA BL PRA DL QUE E O REGS QUE DEVE SER LIDO
    MOV DL,BL
    ;ADICIONA 48 PRA TABELA ASC
    ADD DL,48
    INT 21H
    ;REPETE
    MOV AH,2
    MOV DL,BH
    ADD DL,48
    INT 21H
   
    RET
TIROS_RESTANTES ENDP
 
END MAIN
